// Generated by CoffeeScript 1.8.0
(function() {
  var foot_with_buttons, get_footer;

  get_footer = function() {
    return "<div class=\"row-fluid footer\">\n        <p class=\"text-center\"> goodogood, goodagood, Andrew &reg; &copy;  <p>\n</div>";
  };

  module.exports.get_footer = get_footer;

  foot_with_buttons = "\n<div class=\"row-fluid footer\">\n    <div class=\"buttons\">\n        <a href=\"/file/md-with-local-files/intro/public/intro.md\" class=\"button\"> Background</a>\n        <a class=\"button\" href=\"/logout\"> Logout </a>\n    </div>\n    <p>\n        goodogood, goodagood, Andrew, &copy; \n    </p>\n</div>\n";

  module.exports.foot_with_buttons = foot_with_buttons;

}).call(this);
