// Generated by CoffeeScript 1.8.0
(function() {
  var File_info_css_file_name, Folder_list_css_file_name, Goodagood_config_folder, check_read_css, check_read_default_file_css, check_read_default_fold_css, check_read_file_info_css, filter_out_user_name, folder_module, p, path, read_css_file_for_file_info, read_css_file_of_folder, read_default_css_file_for_file_info, read_default_css_file_of_folder, read_file_css, read_folder_css, tool, u;

  u = require("underscore");

  path = require("path");

  folder_module = require("./folder-v5.js");

  Goodagood_config_folder = 'goodagood/etc';

  Folder_list_css_file_name = 'folder.css';

  File_info_css_file_name = 'file.css';

  p = console.log;

  read_css_file_of_folder = function(folder_path) {
    return folder_module.retrieve_folder(folder_path).then(function(folder) {
      if (folder.file_exists(Folder_list_css_file_name)) {
        return folder.read_file_by_name(Folder_list_css_file_name);
      } else {
        return Promise.resolve(null);
      }
    });
  };

  filter_out_user_name = function(name) {
    var user_name, username;
    username = name || '';
    if (!u.isString(user_name)) {
      return null;
    }
    if (u.isEmpty(user_name)) {
      return null;
    }
    while (user_name.indexOf('/') === 0) {
      user_name = user_name.slice(1);
    }
    if (user_name.indexOf('/') > 0) {
      user_name = user_name.split("/")[0];
      p('In "filter out user name", user name is: ', user_name);
    }
    return user_name;
  };

  read_default_css_file_of_folder = function(name_or_path) {
    var default_folder, user_name;
    user_name = filter_out_user_name(name_or_path);
    if (user_name === null || user_name === '') {
      return Promise.resolve(null);
    }
    default_folder = path.join(user_name, Goodagood_config_folder);
    return read_css_file_of_folder(default_folder);
  };

  read_folder_css = function(folder_path) {
    return read_css_file_of_folder(folder_path).then(function(css_str) {
      if (css_str === null || css_str === '') {
        p('go for default css file.');
        return read_default_css_file_of_folder(folder_path);
      } else {
        return css_str;
      }
    });
  };

  read_css_file_for_file_info = function(folder_path) {
    var file_name;
    file_name = File_info_css_file_name;
    return folder_module.retrieve_folder(folder_path).then(function(folder) {
      if (folder.file_exists(File_info_css_file_name)) {
        return folder.read_file_by_name(file_name);
      } else {
        return Promise.resolve(null);
      }
    });
  };

  read_default_css_file_for_file_info = function(name_or_path) {
    var default_folder, user_name;
    user_name = filter_out_user_name(name_or_path);
    if (user_name === null || user_name === '') {
      return Promise.resolve(null);
    }
    default_folder = path.join(user_name, Goodagood_config_folder);
    return read_css_file_for_file_info(default_folder);
  };

  read_file_css = function(folder_path) {
    return read_css_file_for_file_info(folder_path).then(function(css_str) {
      if (css_str === null || css_str === '') {
        return read_default_css_file_for_file_info(folder_path);
      } else {
        return css_str;
      }
    });
  };

  module.exports.read_css_file_of_folder = read_css_file_of_folder;

  module.exports.read_default_css_file_of_folder = read_default_css_file_of_folder;

  module.exports.read_folder_css = read_folder_css;

  module.exports.read_css_file_for_file_info = read_css_file_for_file_info;

  module.exports.read_default_css_file_for_file_info = read_default_css_file_for_file_info;

  module.exports.read_file_css = read_file_css;

  tool = require("../myutils/test-util.js");

  check_read_css = function(name) {
    name = name || 'abc';
    return read_css_file_of_folder(name).then(function(str) {
      p('content should be: ', str);
      return tool.stop();
    });
  };

  check_read_default_fold_css = function(name) {
    name = name || 'abc';
    return read_default_css_file_of_folder(name).then(function(str) {
      p("default css file:\n", str);
      return tool.stop();
    });
  };

  check_read_file_info_css = function(username) {
    username = username || 'abc';
    return read_css_file_for_file_info(username).then(function(what) {}).then(function() {
      return tool.stop();
    });
  };

  check_read_default_file_css = function(user_name) {
    user_name = user_name || 'abc';
    return read_default_css_file_for_file_info(user_name).then(function(css) {
      p(css);
      return tool.stop();
    });
  };

  if (require.main === module) {
    check_read_default_file_css();
  }

}).call(this);
