// Generated by CoffeeScript 1.8.0
(function() {
  var File_list_a, chk_r, p, render_file_list, tpl;

  tpl = require("../myutils/tpl.js");

  File_list_a = "\n<ul id=\"file-listing-ul\" class=\"folder-list list-unstyled <%= user_role %>\" data-cwd=\"<%= folder_path %>\">\n    <%= file_list %>\n</ul>\n";

  render_file_list = function(context, callback) {
    return tpl.u_render_str(File_list_a, context, callback);
  };

  module.exports.render_file_list = render_file_list;

  p = console.log;

  chk_r = function() {
    var context;
    context = {
      file_list: '',
      user_role: '',
      folder_path: ''
    };
    return render_file_list(context, function(err, ul) {
      p(err, ul);
      return process.exit();
    });
  };

  if (require.main === module) {
    chk_r();
  }

}).call(this);
