// Generated by CoffeeScript 1.10.0
(function() {
  var File_info_li, Key_value_li, handlebars, kv_li, p;

  handlebars = require('handlebars');

  p = console.log;

  Key_value_li = '<li class="key">\n    <span class="key">{{{key}}}</span> :\n    <span class="value">{{{value}}}</span>\n</li>';

  File_info_li = '<li class="filename"> <span>Name</span>: {{{name}}} </li>';

  kv_li = function(key, value) {
    var context, html, tpl;
    tpl = handlebars.compile(Key_value_li);
    context = {
      key: key,
      value: value
    };
    html = tpl(context);
    return html;
  };

  module.exports.kv_li = kv_li;

}).call(this);
