// Generated by CoffeeScript 1.8.0
(function() {
  var assert, avatar, u, username;

  assert = require("assert");

  u = require("underscore");

  avatar = require('../users/avatar.js');

  username = 'abc';

  describe("test avatar.js (user),", function() {
    return it("should gives object,", function(done) {
      return avatar.make_user_obj(username, function(user) {
        assert(!u.isEmpty(user));
        return user.pass_attr(function(err, attrs) {
          assert(u.isNull(err));
          assert(!u.isNull(attrs));
          assert(!u.isEmpty(attrs));
          return done();
        });
      });
    });
  });

  describe("test avatar.js,", function() {
    return it("flag can be up,", function(done) {
      return avatar.make_user_obj(username, function(user) {
        return user.flag_up('test-flag', function(ok, flag_down) {
          assert(ok, 'flag should be up');
          if (ok) {
            flag_down();
          }
          return done();
        });
      });
    });
  });

}).call(this);
