// Generated by CoffeeScript 1.8.0
(function() {
  var assert, folder, folder_list, folder_name, p, u;

  u = require('underscore');

  assert = require('assert');

  folder = require('../aws/folder-v1.js');

  p = console.log;

  folder_list = ['abc'];

  folder_name = 'abc';

  describe('coffee test mocha is working,', function() {
    return it('can make a few assert exception to make sure it keeps firing, ', function() {
      assert.equal(1, 1, 'obviously equal');
      assert.ok(true, 'obviously ok');
      return assert.ok('ok', 'obviously ok');
    });
  });

  describe('new folder testing,', function() {
    return it('get non-empty instance, has meta ', function(done) {
      return folder.make_s3folder(folder_name, function(err, f) {
        assert(!u.isEmpty(f));
        return f.retrieve_old_folder_meta(function(err, what) {
          var m;
          m = f.get_meta();
          assert(u.isObject(m));
          assert(!u.isEmpty(m.files));
          return done();
        });
      });
    });
  });

}).call(this);
