// Generated by CoffeeScript 1.8.0
(function() {
  var Md_with_local_tpl, c_file_in_m, fill_in_markdown, fs, handlebars, p, path, tpl;

  fs = require('fs');

  path = require('path');

  handlebars = require('handlebars');

  tpl = require("../myutils/tpl.js");

  p = console.log;

  Md_with_local_tpl = 'mdhtml.html';

  fill_in_markdown = function(template_name, context, callback) {
    var file_path;
    context = context || {};
    file_path = path.join(__dirname, template_name);
    return tpl.render_template(file_path, context, callback);
  };

  module.exports.fill_in_markdown = fill_in_markdown;

  c_file_in_m = function() {
    var context;
    context = {
      html_of_markdown: '<h1> i am markdown </h1>',
      ok: '--ok--'
    };
    return fill_in_markdown('mdhtml.html', context, function(err, html) {
      p(err, html.slice(0, 300));
      return fs.writeFile('/tmp/mdtest.html', html, 'utf-8', function(err, write) {
        return p('file write, ', err);
      });
    });
  };

  if (require.main === module) {
    c_file_in_m();
  }

}).call(this);
