// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, config, p, path, promise_to_wait, sleep, stop, u;

  path = require("path");

  Promise = require("bluebird");

  u = require("underscore");

  config = {};

  module.exports.config = config;

  config.user_name = 'abc';

  config.folder_path = 'abc';

  config.file_name = 'txt22';

  config.folder_name = config.folder_path;

  config.file_path = path.join(config.folder_path, config.file_name);

  p = console.log;

  stop = function(period) {
    var milli_seconds;
    period = period || 1;
    if (!u.isNumber(period)) {
      period = 1;
    }
    milli_seconds = period * 1000;
    return setTimeout(process.exit, milli_seconds);
  };

  promise_to_wait = function(seconds) {
    var milli_seconds;
    seconds = seconds || 1;
    if (!u.isNumber(seconds)) {
      seconds = 1;
    }
    milli_seconds = seconds * 1000;
    return new Promise(function(resolve) {
      return setTimeout(resolve, milli_seconds);
    });
  };

  sleep = promise_to_wait;

  module.exports.p = p;

  module.exports.stop = stop;

  module.exports.promise_to_wait = promise_to_wait;

  module.exports.sleep = sleep;

  if (require.main === module) {
    wait(3).then(function(what) {
      return p('wait how long? ', what);
    });
  }

}).call(this);
