// Generated by CoffeeScript 1.8.0
(function() {
  var assert, folder, folder_list, folder_name, p, u;

  u = require('underscore');

  assert = require('assert');

  folder = require('../aws/folder-v2.js');

  p = console.log;

  folder_list = ['abc'];

  folder_name = 'abc';

  describe('coffee test mocha is working,', function() {
    return it('can make a few assert exception to make sure it keeps firing, ', function() {
      assert.equal(1, 1, 'obviously equal');
      assert.ok(true, 'obviously ok');
      return assert.ok('ok', 'obviously ok');
    });
  });

  describe('new folder testing,', function() {
    return it('get non-empty instance, has meta ', function() {
      var f, m;
      f = new folder.S3Folder('kkk');
      assert(!u.isEmpty(f));
      m = f.get_meta();
      return assert(u.isObject(m));
    });
  });


  /*
  describe 'Retrieve folder,' , ->
      name = folders[0]
      it 'should get folder obj,', (done) ->
        s3folder.retrieve_folder  name, (err, folder_obj) ->
            assert not  err, "err after retrieve folder: #{name}" + name
            assert not  u.isNull(folder_obj), 'folder should not be null'
  
            meta = folder_obj.get_meta()
  
            assert(typeof meta != 'undefined')
            assert u.isObject(meta)
            assert not u.isNull (meta)
            done()
   */

}).call(this);
