// Generated by CoffeeScript 1.8.0
(function() {
  var Folder, f;

  Folder = (function() {
    function Folder(name, type) {
      this.name = name;
      this.type = type;
    }

    Folder.prototype.show_name = function() {
      return console.log(this.name);
    };

    Folder.prototype.show_type = function() {
      return console.log(this.type);
    };

    return Folder;

  })();

  f = new Folder('tmp', 'simple');

  console.log(f.name, f.type);

  f.name = 'another';

  console.log(f.name, f.type);

}).call(this);
