// Generated by CoffeeScript 1.8.0
(function() {
  var a, bucket, make_new_user_data, request_new_user_account, task;

  a = require("./a.js");

  bucket = require('../aws/bucket.js');

  task = require('../myutils/job.js');

  request_new_user_account = function(info, callback) {
    var job;
    make_new_user_data(info);
    job = JSON.stringify(info);
    return bucket.write_json(info.s3key, info, function(err, reply) {
      if (err) {
        log28('write file info to s3 ERR', [info.s3key, info]);
        return callback(err, null);
      }
      return task.pub_task(task.channel, job, callback);
    });
  };

  make_new_user_data = function(info) {
    info.what = "new-user-info";
    info.timestamp = Date.now();
    info.uuid = myutil.get_uuid();
    info.s3key = path.join(myconfig.new_user_prefix, info.username);
    return info;
  };

}).call(this);
