#!/usr/bin/expect

# easy tool by 'expect' to jump to points.

spawn node
expect ">"
send "var p = console.log;\r"
expect ">"

#send ".load  ./validate-name.js\r"
send ".load  ./u-validate-name.js\r"

expect "ok start interact:"
interact
