// Generated by CoffeeScript 1.8.0
(function() {
  var assemble_file_info_html, css, filelist, mytemplate, p, path, stop;

  path = require("path");

  css = require('../aws/css-file.js');

  mytemplate = require('./template.js');

  filelist = require('../hrouters/file-list-v2.js');

  p = console.log;

  stop = function(time) {
    time = time || 500;
    return setTimeout(process.exit, time);
  };

  assemble_file_info_html = function(meta, info_html, callback) {
    var cwd, username;
    username = meta.owner;
    if (meta.dir != null) {
      cwd = meta.dir;
    } else {
      cwd = path.dirname(meta.path);
    }
    return css.read_file_css(cwd).then(function(frame_css) {
      var contexts, cwd_chain, html_elements;
      cwd_chain = filelist.path_to_chain(cwd);
      contexts = {
        body: {
          file_meta: info_html,
          cwd: cwd,
          cwd_chain: cwd_chain,
          file_name: meta.name
        },
        header: {
          username: username
        },
        frame: {
          css: frame_css
        }
      };
      p('file meta in "assemble file info html" ', info_html);
      html_elements = {
        body: 'file-info-a.html',
        header: 'goodheader.html',
        navbar: 'people-file-navtabs.html',
        script: 'file-info-a-script.html',
        frame: 'frame-a.html'
      };
      return mytemplate.assemble_html(html_elements, contexts, function(html) {
        return callback(html);
      });
    });
  };

  module.exports.assemble_file_info_html = assemble_file_info_html;

}).call(this);
