#!/bin/bash

# forward (http) 80 to 9090, where node.js listenning.  
# The 2nd is for request from localhost

## Change this file to executable.
## Create /etc/init/myport.conf
## 
## sudo vim /etc/init/myport.conf
## 
## with content like the following:
## 
##     description     "forward port 80 to 9090 for muji project"
##     start on startup
##     task
##     exec /path/to/this/file/name
##     #currently:  /home/ubuntu/workspace/gg/plain/myutils/port-forward-0404


# forward 80 to 9090
sudo iptables -t nat -I PREROUTING -p tcp        --dport 80 -j REDIRECT --to-ports 9090
sudo iptables -t nat -I OUTPUT     -p tcp -o lo  --dport 80 -j REDIRECT --to-ports 9090

# 2016 0109
# forward 443 to 9099
sudo iptables -t nat -I PREROUTING -p tcp        --dport 443 -j REDIRECT --to-ports 9099
sudo iptables -t nat -I OUTPUT     -p tcp -o lo  --dport 443 -j REDIRECT --to-ports 9099

# 2016 0305
# forward 9017 to mongodb server's localhost:27017
#autossh -L 9017:localhost:27017 ubuntu@10.134.145.167
#autossh -L 9017:localhost:27017 -L 6379:localhost:6379 ubuntu@10.134.161.155
## how about keep port number? 2016 0411
autossh -L 27017:localhost:27017 -L 6379:localhost:6379 ubuntu@10.134.161.155

